# Generated by Django 5.1.6 on 2025-03-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_alter_genre_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('flag', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
