# Generated by Django 5.1.6 on 2025-03-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_alter_country_options_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_orig', models.CharField(max_length=64)),
                ('title_cz', models.CharField(blank=True, max_length=64, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('released_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('actors', models.ManyToManyField(blank=True, related_name='acting', to='viewer.creator')),
                ('countries', models.ManyToManyField(blank=True, related_name='movies', to='viewer.country')),
                ('directors', models.ManyToManyField(blank=True, related_name='directing', to='viewer.creator')),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='viewer.genre')),
            ],
            options={
                'ordering': ['title_orig', 'released_date'],
            },
        ),
    ]
